### ISSUE TITLE
Add warning for depth failing clip test

### ISSUE THREAD

**Issue by nice-sprite** [baldurk/renderdoc-contrib#5]
When depth test is disabled and the projection matrix has swapped znear and zfar, RenderDoc will still show that the depth test failed in the texture viewer overlay. What is actually happening is the depth value is outside [0, 1] and getting clipped (due to the swapped znear and zfar). I think this can be narrowed down in WhereIsMyDraw with at least a warning to check camera matrix for accidentally swapped znear and zfar when WhereIsMyDraw detects that depth test failed even though its disabled.
![image](https://github.com/baldurk/renderdoc-contrib/assets/17211039/d4dc1a65-8a8d-4f35-b66a-d2d3b00d5112)

**Comment by baldurk** [comment]
There was already a check for clipping and it doesn't matter if you are using reverse projection or not, the crucial part was that depth testing was off - it was incorrectly only checking for clipping-failures if depth testing was enabled. In future if you're reporting a bug like this please include an example capture to make it easier to see what the problem was.
